SELECT DISTINCT Z.SK_ID_CURR, X.SK_ID_CURR, Z.CODE_GENDER, X.NAME_CONTRACT_STATUS
FROM vix.hci_application AS Z
INNER JOIN vix.hci_previous AS X
ON Z.SK_ID_CURR = X.SK_ID_CURR
WHERE Z.TARGET = 0
AND Z.CODE_GENDER = 'F'
AND NOT Z.CNT_CHILDREN = 0
AND X.NAME_CONTRACT_STATUS = 'Approved'
ORDER BY X.SK_ID_CURR;

SELECT DISTINCT Z.SK_ID_CURR, X.SK_ID_CURR, Z.CODE_GENDER, Z.CNT_CHILDREN, Z.TARGET, X.NAME_CONTRACT_TYPE, COUNT(*) AS TOTAL
FROM vix.hci_application AS Z
INNER JOIN vix.hci_previous AS X
ON Z.SK_ID_CURR = X.SK_ID_CURR
GROUP BY X.NAME_CONTRACT_TYPE
/*HAVING Z.CODE_GENDER = 'F'
AND Z.TARGET = 0
AND NOT Z.CNT_CHILDREN = 0*/
ORDER BY TOTAL DESC;

SELECT DISTINCT Z.SK_ID_CURR, X.SK_ID_CURR, Z.CODE_GENDER, X.NAME_CONTRACT_STATUS
FROM vix.hci_application AS Z
INNER JOIN vix.hci_previous AS X
ON Z.SK_ID_CURR = X.SK_ID_CURR
WHERE Z.TARGET = 0
AND Z.CODE_GENDER = 'F'
AND NOT Z.CNT_CHILDREN = 0
AND X.NAME_CONTRACT_STATUS = 'Approved';
